# Configuration for multipage document experiments in AutoTransformers. 
# More scan-like, larger blocks of text, and uniform size
quality: [50, 95]
landscape: 0
short_size: [1024, 1024]
aspect_ratio: [1.414, 1.414]

# background:
#   image:
#     paths: [resources/background]
#     weights: [1]

#   effect:
#     args:
#       # gaussian blur
#       - prob: 1
#         args:
#           sigma: [0, 10]

document:
  fullscreen: 0
  landscape: 0
  short_size: [1024, 1024]
  aspect_ratio: [1.414, 1.414]

  paper:
    image:
      paths: [resources/paper]
      weights: [1]
      alpha: [0, 0.2]
      grayscale: 1
      crop: 1

  content:
    margin: [0, 0.1]
    text:
      - path: resources/corpus/enwiki.txt
        prob: 1
    font:
      paths: [resources/font/en]
      weights: [1]
      bold: 0
    layout:
      text_scale: [0.03, 0.05]
      max_row: 4
      max_col: 3
      fill: [.3, .4]
      full: 0.1
      align: [left, center, right]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [.3, .4]
      stack_full: 0.1
    textbox:
      fill: [1, 1]
    textbox_color:
      prob: 0.2
      args:
        gray: [0, 64]
        colorize: 0
    content_color:
      prob: 0
      args:
        gray: [0, 64]
        colorize: 1

  effect:
    args:
      # elastic distortion
      - prob: 1
        args:
          alpha: [0, 1]
          sigma: [0, 0.5]
      # gaussian noise
      - prob: 1
        args:
          scale: [0, 8]
          per_channel: 0
      # perspective
      # - prob: 1
      #   args:
      #     weights: [750, 50, 50, 25, 25, 25, 25, 50]
      #     args:
      #       - percents: [[0.75, 1], [0.75, 1], [0.75, 1], [0.75, 1]]
      #       - percents: [[0.75, 1], [1, 1], [0.75, 1], [1, 1]]
      #       - percents: [[1, 1], [0.75, 1], [1, 1], [0.75, 1]]
      #       - percents: [[0.75, 1], [1, 1], [1, 1], [1, 1]]
      #       - percents: [[1, 1], [0.75, 1], [1, 1], [1, 1]]
      #       - percents: [[1, 1], [1, 1], [0.75, 1], [1, 1]]
      #       - percents: [[1, 1], [1, 1], [1, 1], [0.75, 1]]
      #       - percents: [[1, 1], [1, 1], [1, 1], [1, 1]]

effect:
  args:
    # color
    - prob: 0
      args:
        rgb: [[0, 255], [0, 255], [0, 255]]
        alpha: [0, 0.2]
    # shadow
    - prob: 1
      args:
        intensity: [0, 40]
        amount: [0, 1]
        smoothing: [0.5, 1]
        bidirectional: 0
    # contrast
    - prob: 1
      args:
        alpha: [1, 1.5]
    # brightness
    - prob: 1
      args:
        beta: [-32, 16]
    # motion blur
    - prob: 0.5
      args:
        k: [3, 5]
        angle: [0, 360]
    # gaussian blur
    - prob: 1
      args:
        sigma: [0, 1.5]
